// Camada de tradução PT/EN. O português é a língua-fonte (o app foi escrito em PT), então
// aqui guardamos apenas o inglês por chave — quando lang==='en', usamos estes valores; caso
// contrário, o texto original em PT que já está no componente.

// Indicadores (KPIs) traduzidos por `key` (o mesmo key definido em deriveMetrics). Tradução
// correta para o vocabulário de RH/People Analytics em inglês.
export const INDICATORS_EN = {
  headcount: 'Active headcount',
  admissoes: 'Hires (month)',
  desligamentos: 'Terminations (month)',
  turnover: 'Monthly turnover',
  absenteismo: 'Absenteeism',
  horasExtras: 'Overtime cost',
  custoPessoal: 'Personnel cost (payroll)',
  diversidade: 'Women in workforce',
  tempoContratacao: 'Average time to hire',
  tempoEmpresa: 'Average tenure',
};

// Navegação por rota (label em inglês). Em PT usamos o label original do componente.
export const NAV_EN = {
  '/': 'Overview',
  '/meu-painel': 'My Dashboard',
  '/produtividade': 'Productivity',
  '/workforce': 'Workforce',
  '/turnover': 'Turnover',
  '/recruitment': 'Recruitment',
  '/absenteeism': 'Absenteeism',
  '/overtime': 'Overtime',
  '/atestados': 'Medical Leave',
  '/aso': 'Occupational Exams',
  '/seguranca': 'Workplace Safety',
  '/epi': 'PPE Management',
  '/nrs': 'Safety Training (NRs)',
  '/diversity': 'Diversity',
  '/pcd': 'Disability Quota',
  '/aprendizes': 'Apprentices',
  '/disciplinar': 'Disciplinary Actions',
  '/chamados': 'HR Tickets',
  '/trabalhista': 'Labor Claims',
  '/posicionamento': 'Salary Positioning',
  '/training': 'Training',
  '/performance': 'Performance',
  '/organograma': 'Org Chart',
  '/gestor': 'Manager View',
  '/copilot': 'Íris AI',
  '/planning': 'Planning',
  '/orcamento': 'Budget',
  '/gatilhos': 'Alerts',
  '/reports': 'Reports',
  '/funcionarios': 'Employees',
  '/configuracoes': 'Settings',
  '/sobre': 'About',
};

// Strings de UI por chave (com PT e EN). Use t('chave') no componente.
export const UI = {
  'nav.overview': { pt: 'Overview', en: 'Overview' },
  'nav.myPanel': { pt: 'Meu Painel', en: 'My Dashboard' },
  'nav.dashboards': { pt: 'Dashboards', en: 'Dashboards' },
  'nav.tools': { pt: 'Ferramentas', en: 'Tools' },
  'nav.settings': { pt: 'Configurações', en: 'Settings' },
  'nav.about': { pt: 'Sobre a empresa', en: 'About the company' },

  // Executive summary
  'exec.indicator': { pt: 'Indicador', en: 'Indicator' },
  'exec.prevMonth': { pt: 'Mês anterior', en: 'Prev. month' },
  'exec.currMonth': { pt: 'Mês atual', en: 'Current month' },
  'exec.variation': { pt: 'Variação', en: 'Change' },
  'exec.ytd': { pt: 'Acum. ano (YTD)', en: 'Year to date (YTD)' },
  'exec.target': { pt: 'Meta', en: 'Target' },
  'exec.withinTarget': { pt: 'Dentro da meta', en: 'On target' },
  'exec.offTarget': { pt: 'Fora da meta', en: 'Off target' },
  'exec.targetShort': { pt: 'meta', en: 'target' },
  'exec.perMonth': { pt: '/mês', en: '/mo' },
  'exec.vsPrevYear': { pt: 'vs. ano anterior', en: 'vs. prev. year' },

  // Home / Overview
  'home.title': { pt: 'Overview', en: 'Overview' },
  'home.carMaker': { pt: 'montadora de veículos (dados fictícios)', en: 'car manufacturer (fictitious data)' },
  'home.activeEmployees': { pt: 'colaboradores ativos', en: 'active employees' },
  'home.closing': { pt: 'fechamento de', en: 'closing' },
  'home.execSummary': { pt: 'Resumo executivo do mês', en: 'Monthly executive summary' },
  'home.autoInsights': { pt: 'Insights automáticos', en: 'Automatic insights' },
  'home.autoInsightsSub': { pt: 'Gerados pela Íris a partir dos dados do período', en: 'Generated by Íris from the period data' },
  'home.explore': { pt: 'Explorar dashboards', en: 'Explore dashboards' },

  // Quick links (Home)
  'ql.workforce.desc': { pt: 'Headcount, estrutura e distribuição salarial', en: 'Headcount, structure and pay distribution' },
  'ql.turnover.desc': { pt: 'Rotatividade voluntária e involuntária', en: 'Voluntary and involuntary turnover' },
  'ql.recruitment.desc': { pt: 'Funil, SLA e fontes de candidatos', en: 'Funnel, SLA and candidate sources' },
  'ql.absenteeism.desc': { pt: 'Índice, motivos e tendências', en: 'Rate, reasons and trends' },
  'ql.overtime.desc': { pt: 'Evolução, custo e ranking por diretoria', en: 'Trend, cost and ranking by division' },
  'ql.diversity.desc': { pt: 'Gênero, raça, gerações e liderança', en: 'Gender, race, generations and leadership' },
  'ql.training.desc': { pt: 'Horas, participação e ROI', en: 'Hours, participation and ROI' },
  'ql.performance.desc': { pt: 'Nine box, potenciais e talentos críticos', en: 'Nine box, potentials and critical talent' },

  // Units
  'unit.days': { pt: 'dias', en: 'days' },
  'unit.years': { pt: 'anos', en: 'years' },

  // Common
  'common.language': { pt: 'Idioma', en: 'Language' },
};
